version: '3.9'

services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379

  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - ./volumes/kafka/log:/var/log/kafka

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - ./volumes/zookeeper/log:/var/log/zookeeper

  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    environment:
      MONGO_DATA_DIR: /data/db
      MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_DATABASE: test
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: $mongo_password

  mongo_compass:
    image: mongo-compass:latest
    ports:
      - 8081:8080
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: $mongo_password
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: $mongo_compass_password
    depends_on:
      - mongo

  kafka_ui:
    image: obsidiandynamics/kafka-ui:latest
    ports:
      - 8082:8080
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_USERNAME: admin
      KAFKA_CLUSTERS_0_PASSWORD: $kafka_password
    
